version: "3.7"
services:
  terraform:
    image: hashicorp/terraform:latest
    container_name: infra_terraform
    working_dir: /workspace
    volumes:
      - .:/workspace:cached
      - gcloud-config:/root/.config
  gcloud:
    entrypoint: "gcloud"
    image: google/cloud-sdk:latest
    container_name: infra_gcloud
    working_dir: /workspace
    volumes:
      - .:/workspace:cached
      - gcloud-config:/root/.config
  tflint:
    image: ghcr.io/terraform-linters/tflint
    container_name: infra_tflint
    volumes:
      - .:/data:cached
volumes:
  gcloud-config:
