version: "3.8"
services:
  tfgcloud:
    container_name: infra_tfgcloud
    build:
      context: .
      dockerfile: docker/tfgcloud/Dockerfile
    working_dir: /private-cloud
    tty: true
    volumes:
      - .:/private-cloud:cached
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: bash
    environment:
      HOME: "/private-cloud"
      GOOGLE_CREDENTIALS: "/private-cloud/gcp-credential.json"
volumes:
  gcloud-config:
